### ISSUE TITLE
[support] Add passwall

### ISSUE THREAD

**Issue by wangxiaoerYah** [Wason-Fok/AutoBuild-OpenWrt-MT1300#2]
希望增加passwall包
🙏

**Comment by Wason-Fok** [comment]
我觉得在这个路由上跑 Passwall 会很拉跨，毕竟这个 CPU 性能没那么强，所以我就没进行编译。

**Comment by wangxiaoerYah** [comment]
> 我觉得在这个路由上跑 Passwall 会很拉跨，毕竟这个 CPU 性能没那么强，所以我就没进行编译。

好吧，确实这个CPU很拉垮😭
